FreshMart/ViewModels/Cart.cs
using FreshMart.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FreshMart.ViewModels
{
    public class Cart : LayoutCategoryViewModel
    {
        public List<CartItem> CartItems { get; set; }
        public decimal TotalAmount { get; set; }

    }

    public class CartItem : LayoutCategoryViewModel
    {
        public Product Product { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }

    }
}

FreshMart/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreshMart.Data;
using FreshMart.Helper;
using FreshMart.Models;
using FreshMart.Services;
using FreshMart.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FreshMart.Controllers
{

    public class CartController : Controller
    {
        //ApplicationUser appUser;

        private readonly ApplicationDbContext _context;
        private int cartCount;
        private IHttpContextAccessor _httpContextAccessor;
        public CartController(ApplicationDbContext con, IHttpContextAccessor hca)
        {
            _context = con;
            _httpContextAccessor = hca;
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            //var b = User.Identity.Name.ToString();

        }
        [Route("/Cart")]
        public ActionResult Cart()
        {

            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                ViewBag.Message = "Your Cart Is Empty";
                this.cartCount = 0;
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                ViewBag.cart = cart;
                this.cartCount = cart.Count;
                ViewBag.total = cart.Sum(c => c.Product.Price * c.Quantity);
            }
            ViewModelService vms = new ViewModelService(_context, _httpContextAccessor);
            var viewmodel = vms.GetProductViewModel();
            ViewBag.CartCount = this.cartCount;
            return View(viewmodel);
        }

        [Route("Cart/addtocart/{id}")]
        public ActionResult AddToCart(int id)
        {



            //ViewBag.route = Url.RouteUrl(RouteData.Values);
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                var cart = new List<CartItem>();
                var item = new CartItem
                {
                    Product = _context.Products.Find(id),
                    Quantity = 1,

                };
                cart.Add(item);

                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                var sessiondata = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                int index = Exists(cart, id);
                if (index == -1)
                {
                    var item = new CartItem
                    {
                        Product = _context.Products.Find(id),
                        Quantity = 1,

                    };
                    cart.Add(item);
                }
                else
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }

            return RedirectToAction("Cart");
        }

        [Route("Cart/RemoveItem/{id}")]
        public ActionResult RemoveItem(int id)
        {

            var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

            return RedirectToAction("Cart");
        }

        //local function start
        private int Exists(List<CartItem> cart, int id)
        {
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }

        //local function end




    }
}

FreshMart/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreshMart.Data;
using FreshMart.Helper;
using FreshMart.Models;
using FreshMart.Services;
using FreshMart.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FreshMart.Controllers
{
    //    [Authorize]
    public class OrderController : Controller
    {

        //ApplicationUser appUser;

        private readonly ApplicationDbContext _context;
        private int cartCount;
        private Customer customer;
        private IHttpContextAccessor _httpContextAccessor;

        public OrderController(ApplicationDbContext con, IHttpContextAccessor hca)
        {
            _context = con;
            _httpContextAccessor = hca;
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            //var b = User.Identity.Name.ToString();

        }


        [HttpGet]
        [Route("Order/Checkout")]
        public ActionResult Checkout()
        {

            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                ViewBag.Message = "Your Cart Is Empty";
                this.cartCount = 0;
                return RedirectToAction("cart", "Cart");
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                ViewBag.cart = cart;

                this.cartCount = cart.Count;
                ViewBag.total = cart.Sum(c => c.Product.Price * c.Quantity);
            }
            //Cart facts here end.................

            var districts = _context.Districts.ToList();
            var categories = _context.Categories.ToList();
            var domains = _context.Categories.Select(c => c.Domain).Distinct().ToList();
            CartService cs = new CartService(_httpContextAccessor, _context);
            var totalPrice = cs.GetCartTotalPrice();
            var Count = cs.GetCartCount();



            var viewmodel = new OrderViewModel();

            viewmodel.District = districts;

            viewmodel.Category = categories;
            viewmodel.DistinctCat = domains;

            var customer = _context.Customers.Where(c => c.Email == User.Identity.Name);
            if (customer.SingleOrDefault() != null)
            {
                viewmodel.Customer = customer.SingleOrDefault();
            }

            if (User.Identity.Name != null)
            {
                ViewBag.Email = User.Identity.Name;
                viewmodel.Order = new Order
                {
                    Email = User.Identity.Name
                };
            }
            else
            {
                ViewBag.Email = null;
            }

            viewmodel.CartCount = Count;
            viewmodel.TotalPrice = totalPrice;
            viewmodel.Sellers = _context.Sellers.ToList();

            return View(viewmodel);
        }

        [HttpPost]
        public ActionResult Checkout(OrderViewModel ovModel)
        {

            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                return RedirectToAction("Index", "Products");
            }

            var customerChk = _context.Customers.Where(c => c.Email == ovModel.Order.Email);

            if (customerChk.ToList().Count < 1)
            {
                var cust = new Customer();
                cust.Name = ovModel.Order.Name;
                cust.Email = ovModel.Order.Email;
                cust.Phone = ovModel.Customer.Phone;
                cust.DistrictId = ovModel.Order.DistrictId;
                _context.Customers.Add(cust);
                _context.SaveChanges();
                customer = cust;
            }
            else
            {
                customer = _context.Customers.Find(ovModel.Customer.Id);
            }

            var order = new Order
            {
                Name = customer.Name,
                Email = customer.Email,
                DistrictId = customer.DistrictId,
                //fixed portion
                ShippingAddress = ovModel.Order.ShippingAddress,
                PostalCode = ovModel.Order.PostalCode,
                StreetNo = ovModel.Order.StreetNo,
                CustomerId = customer.Id,
                TotalPrice = ovModel.TotalPrice,
                OrderDate = DateTime.Now,
                AccountNo = ovModel.Order.AccountNo,
                TransactionId = ovModel.Order.TransactionId
            };

            _context.Orders.Add(order);
            _context.SaveChanges();


            var cartList = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");

            ViewBag.total = cartList.Sum(c => c.Product.Price * c.Quantity);

            foreach (var item in cartList)
            {
                var order_product = new ProductOrder
                {
                    OrderId = order.Id,
                    ProductId = item.Product.Id,
                    NumberOfProduct = item.Quantity
                };

                _context.ProductOrders.Add(order_product);
                _context.SaveChanges();


                var quantity = _context.Products.Where(c => c.Id == item.Product.Id).SingleOrDefault();
                if (quantity != null)
                {
                    var pro = _context.Products.Find(item.Product.Id);
                    pro.ItemInStock = pro.ItemInStock - order_product.NumberOfProduct;

                    _context.Products.Update(pro);
                    _context.SaveChanges();
                }
            }
            //clear the session now
            HttpContext.Session.Clear();

            var agents = _context.Agents.Where(c => c.DistrictId == order.DistrictId).ToList();
            var random = new Random();
            var index = random.Next(0, agents.Count);
            var agent = agents[index];

            var agentorder = new AgentOrder
            {
                AgentId = agent.Id,
                OrderId = order.Id,
                IsPaid = false,
                IsOnRoute = false,
                IsFullyCompleted = false
            };

            _context.AgentOrders.Add(agentorder);
            _context.SaveChanges();



            TempData["orderSuccess"] = "Your order has been placed successfully!";
            return RedirectToAction("Checkout");
        }

    }
}

FreshMart/Views/Cart/Cart.cshtml
@model FreshMart.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Cart";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<h2 class="text-center" style="margin-bottom:50px">Cart</h2>

@if (TempData["orderSuccess"] != null)
{
    <h3 class="text-center" style="margin-bottom:50px">@TempData["orderSuccess"]</h3>
}

@if (ViewBag.CartCount == 0)
{
    <h1 class="text-center" style="margin-bottom:50px">Your Cart Is Empty</h1>

}



else
{
    <!-- checkout -->
    <div class="checkout">
        <div class="container">
            <h3>Your shopping cart contains: <span style="color: coral; font-size: 25px;">@Model.CartCount </span>Products</h3>
            <!---728x90--->
            <div style='margin: 0 auto;text-align: center;margin-top: 5px;'>
                <script>
                    var allowedNumberOfEboundDynamicAdds = 4;
                    var sizesEboundDynamicAdsDesktop = ['728x90'];
                    var sizesEboundDynamicAdsTablet = ['728x90'];
                    var sizesEboundDynamicAdsMobile = ['320x100'];
                    eboundAdsTagByDevice(sizesEboundDynamicAdsDesktop, sizesEboundDynamicAdsTablet, sizesEboundDynamicAdsMobile, 'ebound_header_tag');

                    if (typeof user_tag_config == 'undefined') {
                        var user_tag_config = {};
                    }
                    user_tag_config['ebound_header_tag'] = {};
                    user_tag_config['ebound_header_tag']['desktop'] = {};
                    user_tag_config['ebound_header_tag']['desktop']['cpm'] = '';
                    user_tag_config['ebound_header_tag']['desktop']['adsCode'] = '';
                    user_tag_config['ebound_header_tag']['tablet'] = {};
                    user_tag_config['ebound_header_tag']['tablet']['cpm'] = '';
                    user_tag_config['ebound_header_tag']['tablet']['adsCode'] = '';
                    user_tag_config['ebound_header_tag']['mobile'] = {};
                    user_tag_config['ebound_header_tag']['mobile']['cpm'] = '';
                    user_tag_config['ebound_header_tag']['mobile']['adsCode'] = '';
                </script>
            </div>

            <div class="checkout-right">
                @using (Html.BeginForm("UpdateItem", "cart"))
                {
                    <table class="timetable_sub">
                        <thead>
                            <tr>
                                <th>SL No.</th>
                                <th>Product</th>
                                <th>Quality</th>
                                <th>Product Name</th>
                                <th>Price</th>
                                <th>Remove</th>
                            </tr>
                        </thead>
                        @{
                            int count = 1;
                        }

                        @foreach (var items in @ViewBag.cart)
                        {
                            <tr class="rem1">
                                <td class="invert">@count</td>
                                <td class="invert-image">
                                    <a href="single.html">
                                        <img style="max-height:60px; max-width:60px;" src="@items.Product.ImagePath" alt=" "
                                             class="img-responsive" />
                                    </a>
                                </td>
                                <td class="invert">
                                    <div class="quantity">
                                        <div class="quantity-select">
                                            <div class=""><span>@items.Quantity</span></div>
                                        </div>
                                    </div>
                                </td>
                                <td class="invert">@items.Product.Title</td>
                                <td class="invert">@items.Product.Price</td>
                                <td class="invert">
                                    <div class="rem">
                                        <a asp-controller="Cart" asp-action="RemoveItem" asp-route-id="@items.Product.Id" class="close1"></a>
                                    </div>
                                </td>
                            </tr>
                            count++;
                        }

                        @if (ViewBag.total == null)
                        {
                            <tr class="rem1" style="height:70px;">
                                <td class="invert glyphicon-bold">Total Price : $0 </td>
                            </tr>
                        }
                        else
                        {
                            <tr class="rem1" style="height:40px; height:70px;">
                                <td class="invert">Total Price : $@ViewBag.total </td>
                            </tr>
                        }



                        <!--quantity-->
                    </table>

                    @*                     <button class="btn btn-default" type="submit"> Update Quantity</button> *@
                }

            </div>


            <div class="checkout-left">
                <a asp-controller="Products" asp-action="Index" class="checkout-left-basket">
                    <h4><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>Continue Shopping</h4>
                </a>
                <div class="checkout-right-basket">
                    <a asp-controller="Order" asp-action="Checkout">
                        <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>Go For Checkout
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!-- //checkout -->

}