FreshMart/Models/CategoryDomain.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FreshMart.Models
{
    public class CategoryDomain
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

FreshMart/Areas/Admin/Controllers/CategoryDomainsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FreshMart.Data;
using FreshMart.Models;

namespace FreshMart.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryDomainsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryDomainsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/CategoryDomains
        public async Task<IActionResult> Index()
        {
            return View(await _context.CategoryDomains.ToListAsync());
        }



        // GET: Admin/CategoryDomains/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/CategoryDomains/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] CategoryDomain categoryDomain)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoryDomain);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoryDomain);
        }

        // GET: Admin/CategoryDomains/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryDomain = await _context.CategoryDomains.SingleOrDefaultAsync(m => m.Id == id);
            if (categoryDomain == null)
            {
                return NotFound();
            }
            return View(categoryDomain);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] CategoryDomain categoryDomain)
        {
            if (id != categoryDomain.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoryDomain);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryDomainExists(categoryDomain.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoryDomain);
        }



        // POST: Admin/CategoryDomains/Delete/5

        [Route("Admin/CategoryDomains/DeleteConfirmed/{id}")]
        public IActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                NotFound();
            }

            var categoryDomain = _context.CategoryDomains.SingleOrDefault(m => m.Id == id);

            var categories = _context.Categories.Where(c => c.Domain == categoryDomain.Name).ToList();

            foreach (var cat in categories)
            {

                _context.Categories.Remove(cat);
                _context.SaveChangesAsync();
            }

            _context.CategoryDomains.Remove(categoryDomain);
            _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        private bool CategoryDomainExists(int id)
        {
            return _context.CategoryDomains.Any(e => e.Id == id);
        }
    }
}

FreshMart/Areas/Admin/Views/CategoryDomains/Create.cshtml
@model FreshMart.Models.CategoryDomain

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            All Categories
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Add New Domain</h3>
                    </div>
                    <!-- /.box-header -->
                    @using (Html.BeginForm("Create", "CategoryDomains", FormMethod.Post))
                    {

                        <div class="box-body">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                @Html.TextBoxFor(c => c.Name, new { @class = "form-control" })
                                @* <input asp-for="Name" class="form-control" /> *@
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    }
                    <!-- /.box-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>

FreshMart/Areas/Admin/Views/CategoryDomains/Edit.cshtml
@model FreshMart.Models.CategoryDomain

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            All Categories
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Update Category</h3>
                    </div>
                    <!-- /.box-header -->
                    @using (Html.BeginForm("Edit", "CategoryDomains", new { id = Model.Id }, FormMethod.Post))
                    {
                        <div class="box-body">
                            <input type="hidden" asp-for="Id" />
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                @Html.TextBoxFor(c => c.Name, new { @class = "form-control" })
                                @* <input asp-for="Name" class="form-control" /> *@
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="box-footer">
                            <input type="submit" value="Save" class="btn btn-default" />

                        </div>
                    }

                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>

FreshMart/Areas/Admin/Views/CategoryDomains/Index.cshtml
@model IEnumerable<FreshMart.Models.CategoryDomain>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}



<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            All Categories
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Hover Data Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                    <th>Take Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", "CategoryDomains", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "DeleteConfirmed", "CategoryDomains", new { id = item.Id })
                                        </td>

                                    </tr>
                                }

                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>