FreshMart/Areas/Admin/Controllers/SellerBuyerManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FreshMart.Data;
using FreshMart.Models;
using Microsoft.AspNetCore.Authorization;

namespace FreshMart.Areas.Admin.Controllers
{

    [Area("Admin")]
    //    [Authorize]
    public class SellerBuyerManagerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SellerBuyerManagerController(ApplicationDbContext context)
        {
            _context = context;
        }




        //SELLER SECTION


        // GET: Admin/SellerBuyerManager
        [Route("Admin/SellerBuyerManager/SellerIndex")]
        public async Task<IActionResult> SellerIndex()
        {

            var applicationDbContext = _context.Sellers.Include(s => s.District);
            return View(await applicationDbContext.ToListAsync());
        }


        //post request
        [Route("Admin/SellerBuyerManager/DeleteSeller/{id}")]
        public IActionResult DeleteSeller(string id)
        {
            var r = _context.Sellers.Find(id);
            if (r == null)
            {
                return NotFound();
            }

            _context.Sellers.Remove(r);
            _context.SaveChanges();


            return RedirectToAction("");
        }

        //SELLER SECTION END



        //REQUEST SECTION

        // GET: Admin/SellerBuyerManager
        [Route("Admin/SellerBuyerManager/RequestIndex")]
        public async Task<IActionResult> RequestIndex()
        {

            var applicationDbContext = _context.SellerRequests.Include(s => s.District);
            ViewBag.seller = _context.Sellers.ToList();

            return View(await applicationDbContext.ToListAsync());
        }

        //post request
        [Route("Admin/SellerBuyerManager/approveseller/{email}")]
        public IActionResult ApproveSeller(string email)
        {
            var r = _context.SellerRequests.Where(s => s.Email.Contains(email));
            if (r.SingleOrDefault() == null)
            {
                return NotFound();
            }

            var request = _context.SellerRequests.Where(s => s.Email.Contains(email)).SingleOrDefault();

            var seller = new Seller
            {
                Name = request.SellerName,
                Email = email,
                CompanyName = request.CompanyName,
                DistrictId = request.DistrictId,
                Phone = request.Phone,
                DateOfBirth = request.DateOfBirth,
                Approval = true
            };
            _context.Sellers.Add(seller);
            _context.SaveChanges();



            var del = _context.SellerRequests.Find(request.Id);
            _context.SellerRequests.Remove(del);
            _context.SaveChanges();

            var applicationDbContext = _context.SellerRequests.Include(s => s.District);
            ViewBag.seller = _context.Sellers.ToList();

            return View("RequestIndex", applicationDbContext);
        }


        //REQUEST SECTION END



        //CUSTOMER SECTION


        // GET: Admin/SellerBuyerManager
        [Route("Admin/SellerBuyerManager/CustomerIndex")]
        public async Task<IActionResult> CustomerIndex()
        {

            var applicationDbContext = _context.Customers.Include(s => s.District);
            return View(await applicationDbContext.ToListAsync());
        }




        //CUSTOMER SECTION END




        // GET: Admin/SellerBuyerManager/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seller = await _context.Sellers
                .Include(s => s.District)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (seller == null)
            {
                return NotFound();
            }

            return View(seller);
        }









        // GET: Admin/SellerBuyerManager/Create
        public IActionResult Create()
        {
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Division");
            return View();
        }

        // POST: Admin/SellerBuyerManager/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Phone,DateOfBirth,DistrictId")] Seller seller)
        {
            if (ModelState.IsValid)
            {
                _context.Add(seller);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(SellerIndex));
            }
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Division", seller.DistrictId);
            return View(seller);
        }









        // GET: Admin/SellerBuyerManager/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seller = await _context.Sellers.SingleOrDefaultAsync(m => m.Id == id);
            if (seller == null)
            {
                return NotFound();
            }
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Division", seller.DistrictId);
            return View(seller);
        }








        // POST: Admin/SellerBuyerManager/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Phone,DateOfBirth,DistrictId")] Seller seller)
        {
            if (id != seller.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(seller);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SellerExists(seller.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(SellerIndex));
            }
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Division", seller.DistrictId);
            return View(seller);
        }










        // GET: Admin/SellerBuyerManager/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seller = await _context.Sellers
                .Include(s => s.District)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (seller == null)
            {
                return NotFound();
            }

            return View(seller);
        }









        // POST: Admin/SellerBuyerManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var seller = await _context.Sellers.SingleOrDefaultAsync(m => m.Id == id);
            _context.Sellers.Remove(seller);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(SellerIndex));
        }

        private bool SellerExists(int id)
        {
            return _context.Sellers.Any(e => e.Id == id);
        }
    }
}

FreshMart/Areas/Admin/Views/SellerBuyerManager/Create.cshtml
@model FreshMart.Models.Seller

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<h2>Create</h2>

<h4>Seller</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DistrictId" class="control-label"></label>
                <select asp-for="DistrictId" class ="form-control" asp-items="ViewBag.DistrictId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FreshMart/Areas/Admin/Views/SellerBuyerManager/CustomerIndex.cshtml
@model IEnumerable<FreshMart.Models.Customer>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            All Products
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Hover Data Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Customer Name</th>
                                    <th>Email</th>
                                    <th>District</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Name</td>
                                        <td>@item.Email</td>
                                        <td>@item.District.Name</td>



                                    </tr>
                                }

                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>

FreshMart/Areas/Admin/Views/SellerBuyerManager/Delete.cshtml
@model FreshMart.Models.Seller

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Seller</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.District)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.District.Division)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FreshMart/Areas/Admin/Views/SellerBuyerManager/Details.cshtml
@model FreshMart.Models.Seller

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Seller</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.District)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.District.Division)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FreshMart/Areas/Admin/Views/SellerBuyerManager/Edit.cshtml
@model FreshMart.Models.Seller

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<h2>Edit</h2>

<h4>Seller</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DistrictId" class="control-label"></label>
                <select asp-for="DistrictId" class="form-control" asp-items="ViewBag.DistrictId"></select>
                <span asp-validation-for="DistrictId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FreshMart/Areas/Admin/Views/SellerBuyerManager/Index.cshtml
@model IEnumerable<FreshMart.Models.Seller>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Phone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateOfBirth)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.District)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.District.Division)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FreshMart/Areas/Admin/Views/SellerBuyerManager/RequestIndex.cshtml
@using FreshMart.Models
@model IEnumerable<FreshMart.Areas.Admin.Models.SellerRequest>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            All Products
        </h1>

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Hover Data Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Seller Name</th>
                                    <th>Email</th>
                                    <th>District</th>
                                    <th>Take Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    var sellers = (List<Seller>)ViewBag.seller;
                                }
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.SellerName</td>
                                        <td>@item.Email</td>
                                        <td>@item.District.Name</td>

                                        <td>
                                            @{
                                                int count = 0;
                                                foreach (var seller in sellers)
                                                {
                                                    if (item.Email == seller.Email)
                                                    {
                                                        count++;
                                                    }
                                                }

                                                if (count > 0)
                                                {
                                                    <span>Approved</span>
                                                }
                                                else
                                                {
                                                    @Html.ActionLink("Accept", "ApproveSeller", "SellerBuyerManager", new { id = item.Email }, new { @class = "btn btn-success" })
                                                }

                                            }

                                        </td>

                                    </tr>
                                }

                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>

FreshMart/Areas/Admin/Views/SellerBuyerManager/SellerIndex.cshtml
@model IEnumerable<FreshMart.Models.Seller>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}





<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            All Products
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Hover Data Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Seller Name</th>
                                    <th>Email</th>
                                    <th>District</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Name</td>
                                        <td>@item.Email</td>
                                        <td>@item.District.Name</td>



                                        <td>
                                            @if (item.Approval == true)
                                            {
                                                <span>
                                                    Approved
                                                </span>
                                            }
                                            else
                                            {
                                                <span> Not Approved</span>
                                            }

                                            @*@Html.ActionLink("Delete", "DeleteSeller", "SellerBuyerManager", new { id = item.Id })*@
                                        </td>

                                    </tr>
                                }

                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>